# -*- coding: utf-8 -*-
"""question model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bRp29_DMQzVBXfM7IsSikNts0-Y8kPmt
"""

class Question:
  def __init__(self, q_test, q_answer):
    self.text = q_test
    self.answer = q_answer