# -*- coding: utf-8 -*-
"""Bank account.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11xjFtq8fKQ9LaEx4OW3byb2cyald2I2N
"""

class BankAccount:
  def __init__(self, owner, balance):
    self.owner = owner
    self.balance = balance

  def deposit(self, amount):
    self.balance += amount
    print(f"Deposited ${amount}. New balance: ${self.balance}")

  def withdraw(self, amount):
    if amount > self.balance:
      print('Insufficient funds')
    else:
      self.balance -= amount
      print(f"Withdrew ${amount}. New balance: ${self.balance}")

  def check_balance(self):
    print(f"Account balance: ${self.balance}")

